In [11]:
import cv2 as op    #图像处理
import numpy as np #数组矩阵处理
import matplotlib.pyplot as plt #灰度图显示

one=np.ones((4,4))
map1 = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],dtype=np.float32)
map2=map1
map=op.remap(one.astype(np.float32),map1,map2,interpolation=op.INTER_LINEAR)

print(one)
print(map)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
import cv2 as op    # 图像处理
import numpy as np # 数组矩阵处理
import matplotlib.pyplot as plt # 灰度图显示

one = np.zeros((4, 4), dtype=np.float32)
one[3,:]=1
map_x=np.ones((4,4),np.float32)
map2 = np.array([[0, 0, 0, 0], [1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]], dtype=np.float32)
map = op.remap(one, map_x, map2, interpolation=op.INTER_LINEAR)

print("Original array:")
print(one)
print("Remapped array:")
print(map)

Original array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]
Remapped array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]


In [1]:
import numpy as np

# 示例二维矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 计算 x 方向上的梯度（水平梯度）
grad_x = np.gradient(matrix, axis=1)

# 计算 y 方向上的梯度（竖直梯度）
grad_y = np.gradient(matrix, axis=0)

print("Original matrix:")
print(matrix)
print("Gradient in x direction:")
print(grad_x)
print("Gradient in y direction:")
print(grad_y)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Gradient in x direction:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Gradient in y direction:
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [2]:
import numpy as np
from scipy import ndimage

# 示例二维矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 计算 x 方向上的梯度（水平梯度）
grad_x = ndimage.sobel(matrix, axis=1)

# 计算 y 方向上的梯度（竖直梯度）
grad_y = ndimage.sobel(matrix, axis=0)

print("Original matrix:")
print(matrix)
print("Gradient in x direction:")
print(grad_x)
print("Gradient in y direction:")
print(grad_y)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Gradient in x direction:
[[4 8 4]
 [4 8 4]
 [4 8 4]]
Gradient in y direction:
[[12 12 12]
 [24 24 24]
 [12 12 12]]
